name: test workflow
on:
    - push
env:
    ECR_REGISTRY: "794038224958.dkr.ecr.eu-central-1.amazonaws.com"
    ECR_REPOSITORY: "pulito-dev-listing-api"
    # IMG_NAME: ${{vars.DOCKERHUB_NAME}}/${{vars.DOCKERHUB_IMG_PREFIX}}-listing-api

jobs:
    build-image:
        runs-on: ubuntu-latest
        steps:
            - 
                uses: actions/checkout@v4
            - 
                uses: benjlevesque/short-sha@v3.0
                id: short-sha
            -
                name: setup QEMU
                uses: docker/setup-qemu-action@v3
            -
                name: setup docker buildx
                uses: docker/setup-buildx-action@v3
            
            # -
            #     name: login to docker hub
            #     uses: docker/login-action@v3
            #     with:
            #         username: ${{vars.DOCKERHUB_NAME}}
            #         password: ${{secrets.DOCKERHUB_PASS}}

            # run the container in the action
            # - 
            #     name: Run Docker container
            #     run: |
            #         docker run -d -p 5000:5000  -e CI=true ${{env.IMG_NAME}}
            #         sleep 30
            #         docker network create web || true
            #         docker run -d \
            #             --network=web \
            #             -p 8000:80 \
            #             -v /var/run/docker.sock:/var/run/docker.sock \
            #             traefik:v2.5 \
            #             --api.insecure=true \
            #             --providers.docker=true \
            #             --providers.docker.exposedbydefault=false

            # -
            #     name: ZAP Scan
            #     uses: zaproxy/action-full-scan@v0.12.0
            #     with:
            #         target: "http://localhost:8000/"
            #         allow_issue_writing: false
            #         fail_action: true

            -
                name: Configure AWS Credentials
                uses: aws-actions/configure-aws-credentials@v4
                with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: ${{ vars.AWS_DEFAULT_REGION }}
            -
                name: Login to Amazon ECR
                id: login-ecr
                uses: aws-actions/amazon-ecr-login@v1
            -
                name: build and push
                uses: docker/build-push-action@v6
                with:
                    push: true
                    platforms: linux/amd64, linux/arm64
                    tags: |
                        ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{steps.short-sha.outputs.sha}}
                        ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
            -
                name: Deploy to EKS
                run: |
                    aws eks update-kubeconfig --region ${{ vars.AWS_DEFAULT_REGION }} --name ${{ vars.AWS_EKS_CLUSTER_NAME }}

                    kubectl set image deployment/listing-api listing-api=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{steps.short-sha.outputs.sha}}




